# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GEDIPipeline
                                 A QGIS plugin
 Download, clip to ROI, subset GEDI data all-in-one QGIS plugin.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-05
        copyright            : (C) 2026 by Leonel Corado
        email                : leonel.corado@uevora.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GEDIPipeline class from file GEDIPipeline.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gedi_pipeline_plugin import GEDIPipeline
    return GEDIPipeline(iface)
